### PR TITLE
Fix displaying of chromosome summary in z menus.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ens-st3 — COMMENTED** [review]
@jyothishnt is this best place to do this or is the Perl Zmenu code better? Do we need an explicit bacteria plugin ?
@mehrnazcharkhchi have you spoken with the bacteria people to see if they know why this functionality is here ?

**Comment by ghost** [comment]
> @jyothishnt is this best place to do this or is the Perl Zmenu code better? Do we need an explicit bacteria plugin ?
> @mehrnazcharkhchi have you spoken with the bacteria people to see if they know why this functionality is here ?

I talked to @jyothishnt  and he showed me the correct usage of this Z-Menu which I'll upload a link for this in the related Jira ticket.

**Comment by jyothishnt** [comment]
@ens-st3 The change here is in the javascript code specific to EG bacteria. It seems this code was missed somehow for bacteria. It is a good idea to check with bacteria team about this change.
But as such the code looks OK to me.

**Review by jyothishnt — APPROVED** [review]
Confirmed with Nishadi

**Pull request merged**
